#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

github=$( echo "wget -Nq https://raw.githubusercontent.com/TeamKeyblade/bin_scripts/chromeos" )

cd ~
mkdir bin
cd bin

$github/LICENSE
$github/NOTICE
$github/README.mkdn
$github/chromeinstall
$github/repo
$github/setupbin
$github/updatebin

mkdir app
cd app

$github/app/gitsubmit
$github/app/mountmtp
$github/app/torrentmaker
$github/app/umountmtp

mkdir ../server
cd ../server

$github/server/dropboxstatus
$github/server/killback
$github/server/nitenite
$github/server/rmdropbox
$github/server/setupdropbox
