#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

github=$( echo "wget -Nq https://raw.githubusercontent.com/TeamKeyblade/bin_scripts/chromeos" )

cd ~
mkdir bin
cd bin

$github/LICENSE
$github/NOTICE
$github/README.mkdn
$github/chromeinstall
chmod +x chromeinstall
$github/repo
chmod +x repo
$github/setupbin
chmod +x setupbin
$github/updatebin
chmod +x updatebin

mkdir app
cd app

$github/app/gitsubmit
chmod +x gitsubmit
$github/app/mountmtp
chmod +x mountmtp
$github/app/torrentmaker
chmod +x torrentmaker
$github/app/umountmtp
chmod +x umountmtp

mkdir ../server
cd ../server

$github/server/dropboxstatus
chmod +x dropboxstatus
$github/server/killback
chmod +x killback
$github/server/nitenite
chmod +x nitenite
$github/server/rmdropbox
chmod +x rmdropbox
$github/server/setupdropbox
chmod +x setupdropbox
