#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if ( grep -q HOME/bin/android $HOME/.bash_profile ); then
	echo ".bash_profile doesn't need to be patched"
else
	sed -i '/PATH"/ a\    PATH="$HOME/bin/android:$HOME/bin/app:$HOME/bin/server:$PATH"' $HOME/.bash_profile
	echo "patched .bash_profile"
fi

if ( ! grep -q HOME/bin/private $HOME/.bash_profile ) && ( find $HOME/bin/private &> /dev/null ); then
	sed -i '/PATH=$HOME"/ a\    PATH="$HOME/bin/private:$PATH"' $HOME/.bash_profile
	echo "patched .bash_profile to include private"
fi
