#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

github=$( echo "wget -Nq https://raw.githubusercontent.com/TeamKeyblade/bin_scripts/chromeos" )

cd ~
mkdir -p bin
cd bin

echo "Grabbing bin folder items"
echo "Grabbing LICENSE file.."
$github/LICENSE
echo "Grabbing NOTICE file.."
$github/NOTICE
echo "Grabbing README.mkdn file.."
$github/README.mkdn
echo "Grabbing repo file.."
$github/repo
chmod +x repo
echo "Grabbing setupbin file.."
$github/setupbin
chmod +x setupbin
echo "Grabbing unsetbin file.."
$github/unsetbin
chmod +x unsetbin
echo "Grabbing updatebin file.."
$github/updatebin
chmod +x updatebin
echo "Finished bin folder items"

mkdir -p app
cd app

echo "Grabbing app folder items"
echo "Grabbing gitsubmit file.."
$github/app/gitsubmit
chmod +x gitsubmit
echo "Grabbing mountmtp file.."
$github/app/mountmtp
chmod +x mountmtp
echo "Grabbing torrentmaker file.."
$github/app/torrentmaker
chmod +x torrentmaker
echo "Grabbing umountmtp file.."
$github/app/umountmtp
chmod +x umountmtp
echo "Finished app folder items"

mkdir -p ../server
cd ../server

echo "Grabbing server folder items"
echo "Grabbing dropboxstatus file.."
$github/server/dropboxstatus
chmod +x dropboxstatus
echo "Grabbing killback file.."
$github/server/killback
chmod +x killback
echo "Grabbing nitenite file.."
$github/server/nitenite
chmod +x nitenite
echo "Grabbing rmdropbox file.."
$github/server/rmdropbox
chmod +x rmdropbox
echo "Grabbing setupdropbox file.."
$github/server/setupdropbox
chmod +x setupdropbox
echo "Finished server folder items"
