#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

yumrepo=$(echo "/etc/yum.repos.d")

if ( find $yumrepo/rpmfusion-free.repo -maxdepth 1 &> /dev/null); then
	echo "rpmfusion free already installed!"
else
	echo "installing rpmfusion free"
	sudo yum localinstall --nogpgcheck http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
fi

if ( find $yumrepo/rpmfusion-nonfree.repo -maxdepth 1 &> /dev/null); then
	echo "rpmfusion nonfree already installed!"
else
	echo "installing rpmfusion nonfree"
	sudo yum localinstall --nogpgcheck http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
fi
