#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
for f in `echo .3gp` `echo .asf` `echo .asx` `echo .avi` `echo .divx` `echo .dvx` `echo .flv` `echo .h264` `echo .m2ts` \
`echo .m4v` `echo .mkv` `echo .mov` `echo .mp4` `echo .mpeg` `echo .mts` `echo .ogm` `echo .rm` `echo .rmvb` `echo .swf` \
`echo .wm` `echo .wmv` `echo .xvid` `echo .yuv`
do
	for video in `find . -print | grep "$f"`
	do
		if ( ! avprobe "$video" |& grep "No such file or directory" &> /dev/null ) \
		|| ( avprobe "$video" |& grep "Video:" &> /dev/null ); then
			if ( avprobe "$video" |& grep "Video: h264" &> /dev/null ) \
			&& ( avprobe "$video" |& grep "Audio: aac" &> /dev/null ); then
				echo "$video's video format is compatible"
			else
				echo "$video's video format is not compatible"
			fi
		fi
	done
#    find . -type f -name "*.flac" -exec bash -c 'avconv -i "$0" -c:a alac "${0/%flac/m4a}"' '{}' \;
done
