#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "Checking if prerequisites are installed"
for f in `echo avconv` `echo dvdauthor` `echo genisoimage`
do
	if ( ! type -a $f &> /dev/null ); then
		if [ $f == "avconv" ]; then
			f="libav-tools"
		fi
		needsinstall="$needsinstall $f"
	fi
done

if [ ! "$needsinstall" ]; then
	echo "All prerequisites are already installed"
else
	echo "Some prerequisites needs to be installed"
	sudo apt-get install $needsinstall
fi

videostandard () {
echo "Is this dvd going to be NTSC or PAL?"
read videostandard

if [ $videostandard == "NTSC" ] || [ $videostandard == "ntsc" ]; then
	export VIDEO_FORMAT=NTSC
	movietodvdstandard=ntsc-dvd
elif [ $videostandard == "PAL" ] || [ $videostandard == "pal" ]; then
	export VIDEO_FORMAT=PAL
	movietodvdstandard=pal-dvd
else
	echo "You did not type in the correct response! try again.."
	echo ""
	videostandard
fi
}
videostandard

echo "Where is the video that is being converted at exactly?"
echo "Example: If it is in your home folder it will be at $HOME"
read whereisvideo

echo "What is the name of the video file? please include extension"
echo "Example: i_am_a_valid_video_file.mp4"
read moviefile

mkdir -p "$whereisvideo"/temp
cd "$whereisvideo"/temp

movietitle=$(echo "$moviefile" | sed s/\.[^\.]*$//)

avconv -i ../"$moviefile" -qscale 1 -vf "scale=640:-1" -target $movietodvdstandard "$movietitle".mpg

dvdauthor -o dvd/ -t "$movietitle".mpg

dvdauthor -o dvd/ -T
genisoimage -dvd-video -v -o ../"$movietitle".iso dvd
cd ..
rm -r temp
