#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "Checking if prerequisites are installed"
for f in `echo avconv` `echo vobcopy`
do
	if ( ! type -a $f &> /dev/null ); then
		if [ $f == "avconv" ]; then
			f="libav-tools"
		fi
		needsinstall="$needsinstall $f"
	fi
done

if [ ! "$needsinstall" ]; then
	echo "All prerequisites are already installed"
else
	echo "Adding necessary repo"
	addrepo ppa:jon-severinsson/ffmpeg

	echo "Some prerequisites needs to be installed"
	sudo apt-get update
	sudo apt-get install $needsinstall
fi

devname=$(blkid | grep udf | sed 's/: .*//')
moviename=$(blkid | grep $devname | sed 's/.*LABEL="//' | sed 's/" .*//')
movietitle=$(echo "$moviename" | sed 's/_/ /g' | sed 's/\(.*\)/\L\1/' | sed 's/\b\(.\)/\u\1/g')

mkdir -p ./temp
cd ./temp

vobcopy -m

cat VIDEO_TS/VTS_01_1.VOB VIDEO_TS/VTS_01_2.VOB VIDEO_TS/VTS_01_3.VOB VIDEO_TS/VTS_01_4.V0B > "$moviename".vob

avconv -i "$moviename".vob -c:v libx264 -c:a ac3 ../"$movietitle".mp4

cd ..
rm -r temp
