#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "Checking if prerequisites are installed"

if ( ! type -a mktorrent &> /dev/null ); then
	needsinstall="mktorrent"
fi

if [ ! "$needsinstall" ]; then
	echo "All prerequisites are already installed"
else
	echo "A prerequisites needs to be installed"
	sudo yum install $needsinstall
fi

echo "You want to make a webseeder?"
read answer

if [ $answer == "yes" ] || [ $answer == "y" ]; then
	echo "What's the link?"
	read link

	webseed=$( echo "-w $link" )
else
	webseed=""
fi

mktorrent -a udp://coppersurfer.tk:6969/announce -a udp://open.demonii.com:1337 $webseed $1
