#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if ( type -a dropbox &> /dev/null ); then
	if [ "$( dropbox status )" == "Dropbox isn't running!" ]; then
		echo "Dropbox isn't running! attempting start"
		dropbox start
	fi
	watch -n .1 dropbox status
elif ( find $HOME/.dropbox/dropbox.py &> /dev/null ); then
	if [ "$( $HOME/.dropbox/dropbox.py status )" == "Dropbox isn't running!" ]; then
		echo "Dropbox isn't running! attempting start"
		$HOME/.dropbox/dropbox.py start
	fi
	watch -n .1 $HOME/.dropbox/dropbox.py status
else
	echo "Dropbox isn't setup correctly"
fi

