#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cd $HOME

if ( ! find $HOME/.dropbox-dist &> /dev/null ); then
	if ( uname -a | grep -q x86_64 ); then
		wget -O dropbox.tar.gz "http://www.dropbox.com/download/?plat=lnx.x86_64"
	else
		wget -O dropbox.tar.gz "http://www.dropbox.com/download/?plat=lnx.x86"
	fi

	tar -xzvf dropbox.tar.gz
	rm dropbox.tar.gz
fi

if ( ! find $HOME/.dropbox/dropbox.py &> /dev/null ); then
	mkdir -p $HOME/.dropbox

	wget -O $HOME/.dropbox/dropbox.py "http://www.dropbox.com/download?dl=packages/dropbox.py"
	chmod 755 $HOME/.dropbox/dropbox.py
fi
