#!/bin/bash
# Copyright (C) 2014 Sean Donovan

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if ( ! find /usr/bin/dropbox &> /dev/null ); then
	echo "Getting Dropbox Master Script"
	sudo wget -O /usr/bin/dropbox "http://www.dropbox.com/download?dl=packages/dropbox.py"
	sudo chmod 755 /usr/bin/dropbox
fi

dropbox start -i

echo "Do you want dropbox to start on login?"
read answer

if [ $answer == "yes" ] || [ $answer == "y" ]; then
	line="@reboot $HOME/.dropbox-dist/dropboxd"
	(crontab -u $( whoami ) -l; echo "$line" ) | crontab -u $( whoami ) -

	echo "Dropbox now set to auto start using cron"
else
	echo "Dropbox not set to auto start"
fi

dropbox start
